/*==============================================================================

# Southclaw's Interactivity Framework (SIF)

## Overview

SIF is a collection of high-level include scripts to make the
development of interactive features easy for the developer while
maintaining quality front-end gameplay for players.

## License

- GPLv3

==============================================================================*/


// Dependencies

#include <streamer>
#include <YSI\y_hooks>
#include <YSI\y_timers>
#include <YSI\y_iterate>


// SIF

#include "SIF\GEID.pwn"
#include "SIF\Core.pwn"
#include "SIF\Button.pwn"
#include "SIF\Door.pwn"
#include "SIF\Item.pwn"
#include "SIF\Inventory.pwn"
#include "SIF\Container.pwn"

#include <SIF\extensions\ItemArrayData.pwn>
#include <SIF\extensions\ItemList.pwn>
#include <SIF\extensions\ItemSerializer.pwn>
#include <SIF\extensions\InventoryDialog.pwn>
#include <SIF\extensions\InventoryKeys.pwn>
#include <SIF\extensions\ContainerDialog.pwn>
#include <SIF\extensions\Craft.pwn>
