{"admin/teleported-to", "Admin %p teleportou-se para si", "Admin %p teleported to you"},
{"common/accept", "Aceitar", "Accept"},
{"common/back", "Voltar", "Back"},
{"common/cancel", "Cancelar", "Cancel"},
{"common/close", "Fechar", "Close"},
{"common/confirm", "Confirmar", "Confirm"},
{"common/distance", "Distancia: %.3f", "Distance: %.3f"},
{"common/empty", "Vazio", "Empty"},
{"common/enter", "Entrar", "Enter"},
{"common/lang-shortcode", "PT", "EN"},
{"common/options", "Opcoes", "Options"},
{"common/register", "Registrar", "Register"},
{"common/select", "Selecionar", "Select"},
{"item/bbq/added-petrol", "1L de gasolina adicionado~n~Tem 10 utilizacoes", "1L of petrol added~n~10 BBQ uses"},
{"item/bbq/cooking", "Churrasqueira acesa ~n~Tempo de cozimento: 30 segundos", "BBQ Lit~n~Cook time: 30 seconds"},
{"item/bbq/food-added", "Comida adicionada", "Food added"},
{"item/bbq/food-cooked", "Essa comida ja foi cozida", "Food already cooked"},
{"item/bbq/needs-petrol", "Essa churrasqueira não tem combustivel.", "Needs fuel from a Petrol Can"},
{"item/body_decomp", "Este corpo esta decomposto demais para ser cortado", "The body has decomposed too much to harvest"},
{"item/body_hardvest", "Alguem ja cortou esse corpo", "Someone already cut this body"},
{"item/campfire/cooking", "Comida adicionada~n~1 minuto para cozinhar", "Food added~n~1 minute cook time"},
{"item/campfire/fuel-added", "1L de gasolina adicionado", "1L of petrol added"},
{"item/campfire/has-fuel", "Fogueira ja tem combustivel", "Campfire already fueled"},
{"item/clothes/invalid-gender", "Essa roupa não e do seu sexo", "Wrong gender for clothes"},
{"item/clothes/invalid-skin", "Não pode usar isso com essa skin!", "You cannot use this using this skin!"},
{"item/container/extra-slots-inventory", "Precisa de %d slots extras no inventario", "Extra %d inventory slots required"},
{"item/container/extra-slots", "Precisa de %d slots extras", "Extra %d slots required"},
{"item/container/inventory_open", "Abrir Inventario", "Open Inventory"},
{"item/container/inventory_title", "Inventario", "Inventory"},
{"item/container/item_options", "Equipar\nUsar\nJogar Item\n", "Equip\nUse\nDrop Item\n"},
{"item/container/move", "Mover para", "Move to"},
{"item/container/options", "Equipar\nMover para inventario >\n", "Equip\nMove to inventory >\n"},
{"item/craft/constructing", "Construindo items...", "Constructing items..."},
{"item/craft/deconstructing", "Desconstruindo item...", "Deconstructing item..."},
{"item/defence/advanced-keypad-installed", "Teclado Avancado Instalado na defesa com Sucesso", "Advanced Keypad installed to defence"},
{"item/defence/building", "Construindo %s...", "Building %s..."},
{"item/defence/code-fast", " >  Você esta digitando codigos muito rapidos, por favor espere %s.", " >  You are entering codes too fast, please wait %s."},
{"item/defence/code-zero", " >  Deixando 0 no code da defesa permitira que a senha seja trocada.", " >  Leaving the code at 0 will allow the code to be set again."},
{"item/defence/destroyed", "Defesa destruida com sucesso!", "Defence disassembled"},
{"item/defence/enter-code", " >  Digite uma senha de 4 digitos para abrir essa defesa.", " >  Enter the 4 digit passcode to open this defence."},
{"item/defence/incorrect-code", " >  Senha incorreta!", " >  Incorrect passcode!"},
{"item/defence/keypad-installed", "Teclado Instalado na defesa com Sucesso", "Keypad installed to defence"},
{"item/defence/limit-reached", " >  ERRO: limite de defesas alcancado, por favor informe um admin.", " >  ERROR: Defence entity limit reached, please inform an admin."},
{"item/defence/modifying", "Modificando %s...", "Modifying %s..."},
{"item/defence/motor-installed", "Motor Instalado na defesa com Sucesso", "Motor installed to defence"},
{"item/defence/moving", "Afaste-se para mover a defesa...", "Moving defence, please stand back."},
{"item/defence/needs-motor", "Você deve instalar um Motor antes de instalar um Teclado!", "You must install a motor before installing a keypad!"},
{"item/defence/not-movable", "Você radio pode instalar um motor nesse tipo de defesa", "You cannot install a motor on that type of defence"},
{"item/defence/removing", "Removendo %s...", "Removing %s..."},
{"item/defence/set-code", " >  Coloque uma senha de 4 digitos para essa defesa.", " >  Set a 4 digit passcode for this defence."},
{"item/drugs/taken", "Tomou %s", "Taken %s"},
{"item/drugs/worn-off", "Efeito de %s passou", "%s has worn off"},
{"item/explosive/bomb_armed_5s", "Bomba Armada por 5 segundos", "Bomb Armed for 5 seconds"},
{"item/explosive/bomb_disarmed", "Bomba Desarmada", "Bomb disarmed"},
{"item/explosive/bomb-armed", "Bomba Armada", "Bomb Armed"},
{"item/explosive/bomb-arming", "Armando Bomba", "Arming Bomb"},
{"item/explosive/phone-synced", " >  Telefones sincronizados, use-o para detonar.", " >  Cell phones synced, use phone to detonate."},
{"item/explosive/proximity-mine-armed", " > Mina de proximidade Armada.", " >  Proximity Mine Primed"},
{"item/explosive/radio-triggered", "Explosivo remoto ativado.", "Triggered remote explosive"},
{"item/fishingrod/line-pulling", "A linha esta puxando...", "The line is tugging..."},
{"item/fishingrod/move-closer", "Você precisa estar proximo a agua", "You need to be closer to the water"},
{"item/fishingrod/no-luck", "Sem sorte!", "Unlucky!"},
{"item/fishingrod/started", "Pescando...~n~Pressione F para cancelar", "Fishing...~n~Press F to cancel"},
{"item/jerrycan-empty", "Este galao esta vazio", "Petrol can empty"},
{"item/locator/failed", "Incapaz de rastrear o telefone.", "Unable to trace the mobile phone"},
{"item/locator/synced", "Localizador sincronizado, agora você pode localizar o telefone.", "Locator synced, you can now locate the phone."},
{"item/machines/refinement/cook-time", "Tempo para cozinhar: %s", "Cook time: %s"},
{"item/machines/refinement/no-items", "Não tem item dentro", "There are no items inside."},
{"item/machines/refinement/not-enough-fuel", "Sem gasolina suficiente. A Maquina requer %.1f por item", "There is not enough fuel. Machine requires %.1f per item."},
{"item/machines/refinement/processing", "A Maquina ja esta processando~n~%s faltando", "The machine is currently processing~n~%s left"},
{"item/machines/refinement/refueling", "Reabastecendo", "Refuelling..."},
{"item/machines/refinement/server-restart", "O server reinicia logo, sem tempo para cozinhar.~n~Tente colocar menos itens dentro para reduzir o tempo.", "The server is restarting soon, not enough time to cook.~n~Try putting less items inside to reduce cook time."},
{"item/molotov/fueled", "Gasolina colocada na garrafa", "Fuel poured in bottle"},
{"item/molotov/petrolcan-no-fuel", "O Galao não tem gasolina.", "Fuel can does not contain petrol"},
{"item/petrolcan/full", "O Galao de gasolina esta cheio", "Fuel can is full"},
{"item/petrolcan/needed", "Você precisa de um Galao de Gasolina", "You need a petrol can"},
{"item/plantpot/bottle-not-water", "A garrafa radio contem agua", "Bottle does not contain water"},
{"item/plantpot/empty", "A garrafa esta vazia", "Bottle is empty"},
{"item/plantpot/harvested", "Planta colhida", "Plant harvested"},
{"item/plantpot/invalid-seed", "Tipo de semente inválida", "Invalid seed type."},
{"item/plantpot/no-plant", "O vaso radio contem uma planta ativa", "Pot doesnt contain an active plant."},
{"item/plantpot/not-grown", "A planta ainda radio cresceu totalmente.", "The plant has not fully grown yet."},
{"item/plantpot/seed-added", "Semente adicionada no vaso", "Added seeds to plant pot"},
{"item/plantpot/water-added", "Adicionado 1 agua no vaso", "Added 1 water to plant pot"},
{"item/plotpole/inserted-left", "Zona Esquerda para Polo %s", "Left Zone for Plot Pole %s"},
{"item/plotpole/inserted", "Zona inserida para Polo %s", "Entered Zone for Plot Pole %s"},
{"item/sign/sign-text", "Digite o texto que ira aparecer abaixo\nEscrevendo '\\' vai comecar uma nova linha.", "Type the text that will shows below\nTyping '\\' will start a new line."},
{"item/sign/sign-title", "Placa", "Sign"},
{"item/stungun/charged", "Arma de choque carregada", "Stun Gun Charged"},
{"item/stungun/discharged", "Arma de choque descarregada", "Out of charge"},
{"item/tent_building", "Montando Tenda", "Building Tent"},
{"item/tent/packing", "Desmontando tenda...", "Removing tent..."},
{"item/tip/Accelerom", "Usado em craftings.", "Used in craftings."},
{"item/tip/AdvancedK", "Segure F com isso enquanto estiver perto de uma defesa construida para torna-la em uma porta protegida com senha.", "Hold ~k~~VEHICLE_ENTER_EXIT~~w~ with this while at a constructed defence to turn it into a key-code protected door."},
{"item/tip/AK47Rifle", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para colocar no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo"},
{"item/tip/Ammo308", "Pressione F nesse item enquanto estiver segurando uma arma ou outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition"},
{"item/tip/Ammo357", "Pressione F neste item enquanto segure uma arma ou uma outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition"},
{"item/tip/Ammo357Tr", "Pressione F nesse item enquanto estiver segurando uma arma ou outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition."},
{"item/tip/Ammo50", "Pressione F neste item enquanto segure uma arma ou uma outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition"},
{"item/tip/Ammo50BMG", "Pressione F nesse item enquanto estiver segurando uma arma ou outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition"},
{"item/tip/Ammo556", "Pressione F neste item enquanto segure uma arma ou uma outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition"},
{"item/tip/Ammo556HP", "Pressione F nesse item enquanto estiver segurando uma arma ou outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition."},
{"item/tip/Ammo556Tr", "Pressione F nesse item enquanto estiver segurando uma arma ou outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition."},
{"item/tip/Ammo762", "Pressione F nesse item enquanto estiver segurando uma arma ou outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition."},
{"item/tip/Ammo9mm", "Pressione F neste item enquanto segure uma arma ou uma outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition"},
{"item/tip/Ammo9mmFM", "Pressione F nesse item enquanto estiver segurando uma arma ou outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition."},
{"item/tip/AmmoBuck", "Pressione F neste item enquanto segure uma arma ou uma outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition"},
{"item/tip/AmmoFlech", "Pressione F nesse item enquanto estiver segurando uma arma ou outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition."},
{"item/tip/AmmoHomeB", "Pressione F nesse item enquanto estiver segurando uma arma ou outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition."},
{"item/tip/AmmoRocke", "Pressione F neste item enquanto segure uma arma ou uma outra caixa de municao para transferir as balas.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ at this item while holding a weapon or another ammo tin to transfer the ammunition"},
{"item/tip/AntiSepBa", "Use isso se você esta sangrando, para não infectar a ferida.", "Use this if you are bleeding, it wont infect the wound."},
{"item/tip/AppleJuic", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/Armour", "Pressione F para vestir como protecao.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ to wear for protection"},
{"item/tip/ArmyHelme", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/AutoInjec", "Diferentes tipos de injetores tem diferentes efeitos, alguns sao bons, e outros não, tenha cuidado!", "Different injector types have different effects, some are good some are bad, be careful!"},
{"item/tip/Backpack", "Pressione ~y~~k~~CONVERSATION_YES~~w~~w~ para colocar nas costas, ou pressione ~y~~k~~CONVERSATION_NO~~w~~w~ enquanto não tem nada nas maos para remover.", "Press ~y~~k~~CONVERSATION_YES~~w~~w~ to put it on your back, or press ~y~~k~~CONVERSATION_NO~~w~~w~ while not holding anything to remove it."},
{"item/tip/Balaclava", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/Banana", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/Bandage", "Você pode colocar atadura nas feridas para parar de sangrar, use isso em você ou em outros jogadores.", "You can bandage wounds and stop bleeding on yourself or other players with this,"},
{"item/tip/BandanaBl", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/BandanaGr", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/BandanaPa", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/BandanaWh", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/Barbecue", "Usada para cozinhar comida, esteja perto dela com comida e pressione F para coloca-la, use gasolina e um isqueiro para cozinhar.", "Used to cook food, stand near with food and press ~k~~VEHICLE_ENTER_EXIT~~w~ to place, use fuel and a lighter to cook"},
{"item/tip/Barstool", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Bat", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/Baton", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/Battery", "Usado para crafts e em puzzles(enigmas).", "Used for crafting and some puzzles."},
{"item/tip/BigSword", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/BoaterHat", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/Boot", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Bottle", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/BowlerHat", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/Bread", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/BreadLoaf", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/Briquette", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Broom", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/Bucket", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Burger", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/BurgerBag", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/BurgerBox", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/BurntLog", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/CakeSlice", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/Camera", "Pode ser usado como um binoculo para espiar jogadores a longa distancia.", "Useful for zooming far for reconnaissance."},
{"item/tip/Campfire", "Para acende-la use gasolina e isqueiro, depois pegue a comida e pressione F para cozinha-la.", "Light with petrol and a lighter, then put food on by holding the food and pressing ~k~~VEHICLE_ENTER_EXIT~~w~ to cook it"},
{"item/tip/CanDrink", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/Cane", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/Canister", "Usado em craftings.", "Used for crafting."},
{"item/tip/Capsule", "Armazene itens aqui e eles serão salvos. ~R~OBS: Caso esteja vazio, será destruído no respawn.", "Store items here and they will be saved. ~R~NOTE: If it is empty, it will be destroyed on respawn."},
{"item/tip/Cereal1", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/Cereal2", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/Chainsaw", "Essa e uma Serra Eletrica a gasolina, extremamente letal.", "This is a petrol powered chainsaw, extremely lethal."},
{"item/tip/Champagne", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/Clothes", "Use-a segurando F.", "Wear these by holding ~k~~VEHICLE_ENTER_EXIT~~w~."},
{"item/tip/CluckinBe", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/CluckingB", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/CodePart", "Um item de puzzle, o numero que aparece perto do nome do item e parte de um dos 4 codigos da senha para abrir uma porta em algum lugar.", "A puzzle item, the number that appears next to the item's name is part of one of the 4 password codes to open a door somewhere."},
{"item/tip/Computer", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/ControlBo", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/CorPanel", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/CowboyHat", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/CrateDoor", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/Cross", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Crowbar", "Use para desmontar defesas, tendas e arrombar carros.", "Use to break defences and tents."},
{"item/tip/Cupboard", "Armazene itens aqui e eles serão salvos. ~R~OBS: Caso esteja vazio, será destruído no respawn.", "Store items here and they will be saved. ~R~NOTE: If it is empty, it will be destroyed on respawn."},
{"item/tip/DataInter", "Usado em craftings.", "Used for crafting."},
{"item/tip/Daypack", "Pressione ~y~~k~~CONVERSATION_YES~~w~~w~ para colocar nas costas, ou pressione ~y~~k~~CONVERSATION_NO~~w~~w~ enquanto não tem nada nas maos para remover.", "Press ~y~~k~~CONVERSATION_YES~~w~~w~ to put it on your back, or press ~y~~k~~CONVERSATION_NO~~w~~w~ while not holding anything to remove it."},
{"item/tip/DeadLeg", "Perna de alguma pessoa morta. Pode ser cozinhada.", "Leg of some dead person. Can be cooked."},
{"item/tip/DesertEag", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/Desk", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Detergent", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/Detonator", "Esse e um item invalido, ignore-o.", "This item is invalid, ignore it."},
{"item/tip/DiaboMask", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/Dice", "Pressione N para jogar o dado.", "Press N to drop the dice and roll it!"},
{"item/tip/Dildo1", "Util tanto para o prazer e tortura.", "Useful for both pleasure and torture."},
{"item/tip/Dildo2", "Util tanto para o prazer e tortura.", "Useful for both pleasure and torture."},
{"item/tip/Dildo3", "Util tanto para o prazer e tortura.", "Useful for both pleasure and torture."},
{"item/tip/Dildo4", "Util tanto para o prazer e tortura.", "Useful for both pleasure and torture."},
{"item/tip/DoctorBag", "Você pode desacelerar sangramentos, regenerar vida e eliminar feridas em você ou nos outros jogadores com isso.", "You can slow bleeding, regenerate blood and heal wounds on yourself or others with this."},
{"item/tip/DogsBreat", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para colocar no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo"},
{"item/tip/DoorBlin", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/Doormat", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/DupleDoor", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/Dynamite", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/EasterEgg", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/EmpPhoneB", "Use um telefone com isso pressionando F para sincronizar telefones, depois use o telefone para detonar com F", ""},
{"item/tip/EmpProxMi", "Esse item não tem utilidade.", ""},
{"item/tip/EmpTimebo", "Uma bomba de proximidade com uma detonacao cronometrada de 5 segundos, pressione F para arma-la.", ""},
{"item/tip/EmpTripMi", "Arme-a no chão pressionando F, arme-a dentro containers clicando Opcoes e em Armar, assim que o container for aberto a bomba detonara.", ""},
{"item/tip/Explosive", "Combine com varios itens mecanicos para criar diferentes tipos de bombas.", "Craft with various mechanical items for different types of bombs."},
{"item/tip/Extinguis", "Use isso para cegar e imobilizar jogadores temporariamente.", "Use this to blind and immobilise players temporarily."},
{"item/tip/fire_hat1", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/fire_hat2", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/FireLight", "Acenda churrasqueira, fogueiras e fogos de artificios com isso.", "Light BBQs, campfires and fireworks with this."},
{"item/tip/FireworkB", "Use um isqueiro com isso para ver alguns fogos de artificios! Ou crie explosivos com isso.", "Use a lighter with this to see some fireworks! Or craft explosives with it."},
{"item/tip/FishRod", "Use para pescar estando proximo a agua.", "Used to fish while near water."},
{"item/tip/FishyFing", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/Flag", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Flamer", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/Flare", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/FlareGun", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Flashligh", "Pressione F para ativa-la.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ to toggle light."},
{"item/tip/Flowers", "Esse item e inutil como arma.", "This item is absolutely useless as a weapon."},
{"item/tip/Fluctuato", "Usado em craftings.", "Used for crafting."},
{"item/tip/FluxCap", "Usado em craftings.", "Used for crafting."},
{"item/tip/Fork", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/FryingPan", "A escolha da arma classica de uma dona de casa dos anos 40.", "The classic weapon choice of a 1940s housewife."},
{"item/tip/Fusebox", "Usado para crafts e em puzzles(enigmas).", "Used for crafting and some puzzles."},
{"item/tip/GarageDoo", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/GasCan", "Use isso para reabastecer veiculos, estando na frente de um segurando F reabastercera o galao segurando F na frente de uma bomba de combustivel.", "Use this to refuel vehicles by standing at the front and holding ~k~~VEHICLE_ENTER_EXIT~~w~ refuel petrol can at fuel pumps by holding ~k~~VEHICLE_ENTER_EXIT~~w~ at one."},
{"item/tip/GasMask", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/GearBox", "Armazene itens aqui e eles serão salvos. ~R~OBS: Caso esteja vazio, será destruído no respawn.", "Store items here and they will be saved. ~R~NOTE: If it is empty, it will be destroyed on respawn."},
{"item/tip/GeigerCou", "Serve para medir a intensidade de radicao", "Measures Radiation Intensity"},
{"item/tip/GolfClub", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/GreenGloo", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Grenade", "Item jogavel que explode, causando um dano massivo alem de desmaios.", "Throwable weapon that explodes, causing massive concussion and knockouts."},
{"item/tip/GrnApple", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/GunCase", "Armazene itens aqui e eles serão salvos. ~R~OBS: Caso esteja vazio, será destruído no respawn.", "Store items here and they will be saved. ~R~NOTE: If it is empty, it will be destroyed on respawn."},
{"item/tip/Gyroscope", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/HackDevic", "Usado para hackear teclados e acessar portas da area 51.", "Used for hacking keypads and accessing doors from 51 area."},
{"item/tip/Ham", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/Hammer", "Use para reparar veiculos, para fazer craftings e para construir defesas.", "Use to repair vehicles by standing at the front and holding ~k~~VEHICLE_ENTER_EXIT~~w~."},
{"item/tip/HandCuffs", "Segure F proximo de um jogador para algema-lo.", "=Hold ~k~~VEHICLE_ENTER_EXIT~~w~ at a player to handcuff them."},
{"item/tip/HardDrive", "Usado para crafts e em puzzles(enigmas).", "Used for crafting and some puzzles."},
{"item/tip/Headlight", "Use isso para reparar os farois de um veiculo estando na frente dele a apertando F.", "Use this to repair vehicle headlights by standing at the front and pressing ~k~~VEHICLE_ENTER_EXIT~~w~"},
{"item/tip/headphone", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/HeartShap", "Pressione ~y~~k~~CONVERSATION_YES~~w~~w~ para colocar nas costas, ou pressione ~y~~k~~CONVERSATION_NO~~w~~w~ enquanto não tem nada nas maos para remover.", "Press ~y~~k~~CONVERSATION_YES~~w~~w~ to put it on your back, or press ~y~~k~~CONVERSATION_NO~~w~~w~ while not holding anything to remove it."},
{"item/tip/Heatseeke", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/HelmArmy", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/HelmMoto", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/HerpDerp", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Holdall", "Armazene itens aqui e eles serão salvos. ~R~OBS: Caso esteja vazio, será destruído no respawn.", "Store items here and they will be saved. ~R~NOTE: If it is empty, it will be destroyed on respawn."},
{"item/tip/HotDog", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/IceCream", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/IceCreamB", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/IedBomb", "Combine com varios itens mecanicos para criar diferentes tipos de bombas.", ""},
{"item/tip/IedPhoneB", "Use um telefone com isso pressionando F para sincronizar telefones, depois use o telefone para detonar com F", ""},
{"item/tip/IedProxMi", "Esse item não tem utilidade.", ""},
{"item/tip/IedTimebo", "Um explosivo com uma detonacao cronometrada de 5 segundos, pressione F para arma-la.", ""},
{"item/tip/IedTripMi", "Arme-a no chão pressionando F, arme-a dentro containers clicando em Opcoes e em Armar, assim que o container for aberto a bomba detonara.", ""},
{"item/tip/InsulDoor", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/InsulPane", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/IoUnit", "Usado em craftings.", "Used for crafting."},
{"item/tip/Ketchup", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/Key", "Pode ser combinado com um motor para fazer um Kit Chaveiro, usado para trancar veiculos.", "Can be combined with a Motor to make a Kit Chaveiro for locking vehicles."},
{"item/tip/Keycard", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Keypad", "Aperte F. Use isso enquanto constroi uma defesa para torna-la uma porta protegida com senha.", "Hold ~k~~VEHICLE_ENTER_EXIT~~w~ with this while at a constructed defence to turn it into a key-code protected door"},
{"item/tip/Knife", "Essa e uma arma branca afiada, efetiva para causar sangramento severo.", "This is a sharp melee weapon, effective at causing severe bleeding."},
{"item/tip/Knife2", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/Knife3", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Knuckles", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/LargeBack", "Pressione ~y~~k~~CONVERSATION_YES~~w~~w~ para colocar nas costas, ou pressione ~y~~k~~CONVERSATION_NO~~w~~w~ enquanto não tem nada nas maos para remover.", "Press ~y~~k~~CONVERSATION_YES~~w~~w~ to put it on your back, or press ~y~~k~~CONVERSATION_NO~~w~~w~ while not holding anything to remove it."},
{"item/tip/LargeBox", "Armazene itens aqui e eles serão salvos. ~R~OBS: Caso esteja vazio, será destruído no respawn.", "Store items here and they will be saved. ~R~NOTE: If it is empty, it will be destroyed on respawn."},
{"item/tip/LaserPoin", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Lemon", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/LenKnocks", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para colocar no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/Locator", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/LockBreak", "Use isso para arrombar veiculos trancados por outros jogadores.", "Use this to break vehicles locked up by other players."},
{"item/tip/Locker", "Armazene itens aqui e eles serão salvos. ~R~OBS: Caso esteja vazio, será destruído no respawn.", "Store items here and they will be saved. ~R~NOTE: If it is empty, it will be destroyed on respawn."},
{"item/tip/Locksmith", "Use isso no lado do motorista segurando F para fazer uma chave manter o veiculo seguro.", "Use this on the driver's side holding F to make a key and keep the vehicle safe."},
{"item/tip/LongPlank", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/M16Rifle", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/M77RMRifl", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para colocar no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo"},
{"item/tip/M9Pistol", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/M9PistolS", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/Mac10", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/Mailbox", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Map", "Com ele no inventario, o seu mapa e liberado.", "Used on inventory, to show your map."},
{"item/tip/MaskGreen", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/MaskRed", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/Meat", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/Meat2", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/MediumBag", "Pressione ~y~~k~~CONVERSATION_YES~~w~~w~ para colocar nas costas, ou pressione ~y~~k~~CONVERSATION_NO~~w~~w~ enquanto não tem nada nas maos para remover.", "Press ~y~~k~~CONVERSATION_YES~~w~~w~ to put it on your back, or press ~y~~k~~CONVERSATION_NO~~w~~w~ while not holding anything to remove it."},
{"item/tip/MediumBox", "Armazene itens aqui e eles serão salvos. ~R~OBS: Caso esteja vazio, será destruído no respawn.", "Store items here and they will be saved. ~R~NOTE: If it is empty, it will be destroyed on respawn."},
{"item/tip/Medkit", "Você pode parar sangramentos e prevenir desmaios em você e em outros jogadores com isso.", "You can stop bleeding and prevent knockouts on yourself or other players with this."},
{"item/tip/MetalBlin", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/MetalFram", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/MetalGate", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/MetalStan", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/MetPanel", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/Microphon", "Esse item não tem utilidade.", "Use of the item not defined."},
{"item/tip/MilkBottl", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/MilkCarto", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/Minigun", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/MobilePho", "Usado em craftings.", "Used in craftings."},
{"item/tip/Model70Ri", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para colocar no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo"},
{"item/tip/Molotov", "Item arremessovel que cria uma area em chamas.", "Throwable weapon that inflicts burn wounds."},
{"item/tip/MolotovEm", "Coloque gasolina nisso para fazer uma bomba de fogo arremissivel.", "Pour petrol into this to make a throwable fire bomb."},
{"item/tip/Money", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/MotionSen", "Usado em craftings.", "Used in craftings."},
{"item/tip/Motor", "Use isso para montar uma base ou em craftings.", "Use this to build a base or in craftings."},
{"item/tip/MP5", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/Mustard", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/Nailbat", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/NightVisi", "Esse e um item invalido, ignore-o.", "This item is invalid, ignore it."},
{"item/tip/Note", "Use este item para escrever notas.", "Use this item to write notes."},
{"item/tip/NULL", "Esse e um item invalido, ignore-o.", "This item is invalid, ignore it."},
{"item/tip/NULL2", "Esse e um item invalido, ignore-o.", "This item is invalid, ignore it."},
{"item/tip/NULL3", "Esse e um item invalido, ignore-o.", "This item is invalid, ignore it."},
{"item/tip/NULL4", "Esse e um item invalido, ignore-o.", "This item is invalid, ignore it."},
{"item/tip/OilCan", "Esse item não tem utilidade.", "Use of the item not defined."},
{"item/tip/OilDrum", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Orange", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/OrangeJui", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/Padlock", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Pager", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Pan", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/ParaBag", "Pressione ~y~~k~~CONVERSATION_YES~~w~~w~ para colocar nas costas, ou pressione ~y~~k~~CONVERSATION_NO~~w~~w~ enquanto não tem nada nas maos para remover.", "Press ~y~~k~~CONVERSATION_YES~~w~~w~ to put it on your back, or press ~y~~k~~CONVERSATION_NO~~w~~w~ while not holding anything to remove it."},
{"item/tip/Parachute", "Pressione ~k~~CONVERSATION_YES~~w~ para equipar, você não pode usar isso enquanto estiver com uma mochila nas costas.", "Press ~k~~CONVERSATION_YES~~w~ to equip, you can't wear this while you are wearing a backpack."},
{"item/tip/Parrot", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/PetrolBom", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Pills", "Diferentes tipos de pilulas tem diferentes efeitos, alguns sao bons, e outros não, tenha cuidado!", "Different pill types have different effects, some are good some are bad, be careful!"},
{"item/tip/PisschBox", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Pizza", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/PizzaBox", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/PizzaHat", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/PizzaOnly", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/PlantPot", "Use isso para plantar sementes, que podem ser regadas usando agua.", "Use this to plant seeds, which can be watered using water."},
{"item/tip/PlotPole", "Usado para salvar todos os itens do chão que estiverem proximos do objeto.", "Used to save all items on the ground that are close to the object."},
{"item/tip/PoliceCap", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/PoliceHel", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/PoolCue", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/PortaCofr", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/PowerSupp", "Usado em craftings.", "Used for crafting."},
{"item/tip/Pumpkin", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/PumpShotg", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/Radio", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/RadioBox", "Esse item não tem utilidade.", "Use of the item not defined."},
{"item/tip/RadioPole", "Usado em craftings.", "Used in craftings."},
{"item/tip/Rake", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/RawFish", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/RedApple", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/RedPanel", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/RefinedMe", "Usado em craftings.", "Used for crafting."},
{"item/tip/RefineMac", "Use essa maquina para refinar itens e transformar em x", "Use this machine to transform x into x."},
{"item/tip/RemoteBom", "Esse e um item invalido, ignore-o.", "This item is invalid, ignore it."},
{"item/tip/RemoteCon", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/RocketLau", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/Rucksack", "Pressione ~y~~k~~CONVERSATION_YES~~w~~w~ para colocar nas costas, ou pressione ~y~~k~~CONVERSATION_NO~~w~~w~ enquanto não tem nada nas maos para remover.", "Press ~y~~k~~CONVERSATION_YES~~w~~w~ to put it on your back, or press ~y~~k~~CONVERSATION_NO~~w~~w~ while not holding anything to remove it."},
{"item/tip/Satchel", "Pressione ~y~~k~~CONVERSATION_YES~~w~~w~ para colocar nas costas, ou pressione ~y~~k~~CONVERSATION_NO~~w~~w~ enquanto não tem nada nas maos para remover.", "Press ~y~~k~~CONVERSATION_YES~~w~~w~ to put it on your back, or press ~y~~k~~CONVERSATION_NO~~w~~w~ while not holding anything to remove it."},
{"item/tip/Sawnoff", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/ScrapMach", "Use essa maquina para transformar x em x", "Use this machine to transform x into x."},
{"item/tip/ScrapMeta", "Usado em craftings.", "Used for crafting."},
{"item/tip/Screwdriv", "Use para reparar veiculos, para fazer craftings e para construir defesas.", "Use to repair vehicles by standing at the front and holding ~k~~VEHICLE_ENTER_EXIT~~w~."},
{"item/tip/SeedBag", "Use isto com um vaso de planta para plantar sementes, use agua para alimentar a planta, você pode criar comida e muito mais!", "Use this with a Plant Pot to plant seeds, use water to feed the plant, you can create food and more!"},
{"item/tip/SemiAutoR", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/Shield", "Isso ira lhe proteger de tiros quando estiver apontado para o atirador.", "This protects you from gunfire when pointed towards the shooter."},
{"item/tip/ShipDoor", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/Sign", "Pressione F para colocar a placa e digite o texto desejado.", "Press ~k~~VEHICLE_ENTER_EXIT~~w~ to place and write on."},
{"item/tip/SignShot", "Use isso para assustar pessoas (não salva depois do respawn).", "Use this to scare people (it doesnt save over restarts)."},
{"item/tip/Sledgeham", "Funciona bem em direcao ao rosto de alguem.", "Works well hurtling towards someones face."},
{"item/tip/SmallBox", "Armazene itens aqui e eles serão salvos. ~R~OBS: Caso esteja vazio, será destruído no respawn.", "Store items here and they will be saved. ~R~NOTE: If it is empty, it will be destroyed on respawn."},
{"item/tip/SmallTabl", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/SniperRif", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/Spade", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/Spanner", "Use para reparar veiculos parando na frente do mesmo e segurando F.", "Use to repair vehicles by standing at the front and holding ~k~~VEHICLE_ENTER_EXIT~~w~."},
{"item/tip/Spas12", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/Spatula", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/SprayPain", "Use isso para pichar seu nome em certas paredes ou para cegar jogadores temporeriamente.", "Use this to spray your name on certain walls or blind players temporarily."},
{"item/tip/StarterMo", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Steak", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/StorageUn", "Usado em craftings.", "Used for crafting."},
{"item/tip/StrawHat", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/StrawHelm", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/StunGun", "Ataque jogadores com isso para desarma-los por 1 minuto.", "Attack players with this to disable them for 1 minute."},
{"item/tip/Suitcase", "Armazene itens aqui e eles serão salvos. ~R~OBS: Caso esteja vazio, será destruído no respawn.", "Store items here and they will be saved. ~R~NOTE: If it is empty, it will be destroyed on respawn."},
{"item/tip/SupplyDro", "Use para chamar uma caixa de suprimentos militares, mas tome cuidado!", "Use this item to call a military supply drop, but be careful!"},
{"item/tip/Sword", "Essa e uma arma branca afiada, efetiva para causar sangramento severo.", "This is a sharp melee weapon, effective at causing severe bleeding."},
{"item/tip/Table", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Taco", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/TallFrame", "Esse item não tem utilidade.", "This item has no utility."},
{"item/tip/Teargas", "Inutil como uma arma porem pode ser usado como distracao ou sinal.", "Useless as a weapon but useful as a distraction or signal."},
{"item/tip/Tec9", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/TentPack", "Use um Martelo com isso para construir uma tenda para armazenar itens.", "Use a hammer with this to build a tent for storage items."},
{"item/tip/ThermalVi", "Esse e um item invalido, ignore-o.", "This item is invalid, ignore it."},
{"item/tip/Timer", "Usado em craftings.", "Used in craftings."},
{"item/tip/TntPhoneB", "Use um telefone com isso pressionando F para sincronizar os telefones, depois use o telefone para detonar com F.", ""},
{"item/tip/TntProxMi", "Esse item não tem utilidade.", ""},
{"item/tip/TntTimebo", "Um explosivo com uma detonacao cronometrada de 5 segundos, pressione F para arma-la.", "An explosive with a timed detonation of 5 seconds, press ~k~~VEHICLE_ENTER_EXIT~~w~ to arm."},
{"item/tip/TntTripMi", "Arme a TNT no chão segurando F, arme-a dentro de container clicando em Opcoes e em Armar, explodindo assim que alguem abra o container.", ""},
{"item/tip/Tomato", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/ToolBox", "Armazene itens aqui e eles serão salvos. ~R~OBS: Caso esteja vazio, será destruído no respawn.", "Store items here and they will be saved. ~R~NOTE: If it is empty, it will be destroyed on respawn."},
{"item/tip/TopHat", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/Torso", "Use uma faca de combate para cortar carnes desse corpo para servir de alimento.", "Use a combat knife to cut flesh from this body for food."},
{"item/tip/TruckCap", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/VehicleWe", "Usado em craftings.", "Used in craftings."},
{"item/tip/WalkingCa", "Essa e uma arma branca robusta, util para desmaiar jogadores.", "This is a blunt melee weapon, useful for knocking players out."},
{"item/tip/WASR3Rifl", "Pressione ~k~~PED_ANSWER_PHONE~~w~ para recarregar, pressione ~k~~CONVERSATION_YES~~w~ para usa-la no coldre e segure ~k~~CONVERSATION_NO~~w~ para remover municao.", "Press ~k~~PED_ANSWER_PHONE~~w~ to reload, press ~k~~CONVERSATION_YES~~w~ to holster and hold ~k~~CONVERSATION_NO~~w~ to remove ammo."},
{"item/tip/WaterMach", "Use essa maquina para purificar uma agua suja.", "Use this machine to purify a dirty water."},
{"item/tip/Wheel", "Use isso para reparar a roda de veiculos, ficando na frente dela e pressionando F.", "Use this to repair vehicle wheels by facing them and pressing ~k~~VEHICLE_ENTER_EXIT~~w~."},
{"item/tip/WheelLock", "Use isso para trancar motos, bicicletas e barcos.", "Use this to lock bikes, bikes and boats."},
{"item/tip/Whisky", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/Wine1", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/Wine2", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/Wine3", "Este item pode conter liquidos. Pressione ~y~F~w~ para tentar beber ou usa-lo.", "This item may contain liquid. Press ~y~F~w~ to try to drink or use it."},
{"item/tip/WitchesHa", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/WoodLog", "Encontre tres destes, coloque-os em uma pilha e use um isqueiro sobre eles para criar um fogo!", "Find three of these, place them in a pile and use a Lighter on them to create a fire!"},
{"item/tip/WoodPanel", "Use uma ~y~Chave de Fenda~w~ nisto para construir uma parede, ou um ~y~Martelo~w~ para construir um chão, segure F para construir.", "Use ~y~Screwdriver~w~ to construct a wall, or a ~y~Hammer~w~ to construct a floor, hold ~k~~VEHICLE_ENTER_EXIT~~w~ to start building."},
{"item/tip/Workbench", "Antes poderia ser usado para craftar itens, onde agora, feito no chão.", "Before it could be used to craft items, where now it's done on the ground."},
{"item/tip/WrappedMe", "Pressione ~y~F~w~ para tentar ingerir ou usa-lo. Mas cuidado, pode te causar nauseas se não for cozinhado antes.", "Press ~y~F~w~ to try to ingest or use it. But be careful, it can make you nauseous if not cooked beforehand."},
{"item/tip/Wrench", "Use para reparar veiculos parando na frente do mesmo e segurando F.", "Use to repair vehicles by standing at the front and holding ~k~~VEHICLE_ENTER_EXIT~~w~."},
{"item/tip/XmasHat", "Pressione ~y~F~w~ para vestir esse acessório.", "Press ~y~F~w~ to wear this accessory."},
{"item/tip/ZorroMask", "Vista isso apertando F.", "Wear this by pressing ~k~~VEHICLE_ENTER_EXIT~~w~ and pretend you are Zorro"},
{"item/tree/cut", "Mantenha F com %s para colher %s", "Hold F with a %s to harvest %s"},
{"item/tweak/move", "Afaste-se do item para move-lo ~n~ Pressione ~k~~SNEAK_ABOUT~ para mostrar o mouse ~n~ Clique em Concluido para concluir", "Move away from item to move it~n~Press ~k~~SNEAK_ABOUT~ to show mouse~n~Click Done to finish"},
{"item/weapon/ammo-mismatch", "Tipos de municao não podem ser misturados.", "Ammo types cant be mixed in tins"},
{"item/weapon/diff-ammo", "Um tipo de municao diferente esta carregado na arma", "A different ammunition type is already loaded in this weapon"},
{"item/weapon/no-ammo", "Não tem municao carregada nessa arma", "There is no ammo loaded in this weapon"},
{"item/weapon/transfer/tin-tin", "Transferiu %d balas da caixa de municao para caixa de municao", "Transferred %d rounds from ammo tin to ammo tin"},
{"item/weapon/transfer/tin-weapon", "Transferiu %d balas de municao tin para arma", "Transferred %d rounds from ammo tin to weapon"},
{"item/weapon/transfer/weapon-tin", "Transferiu %d balas da arma para caixa de municao", "Transferred %d rounds from weapon to ammo tin"},
{"item/weapon/transfer/weapon-weapon", "Transferiu %d balas de arma para arma", "Transferred %d rounds from weapon to weapon"},
{"item/weapon/unloaded", "Arma Descarregada", "Unloaded Weapon"},
{"item/weapon/wrong-calibre", "Calibre errado para arma", "Wrong calibre for weapon"},
{"item/workbench/needed", "Você precisa de uma Mesa de trabalho para combinar isso", "You need a workbench to combine those"},
{"player/account/login/dialog-body", "{FFFFFF}Bem-vindo de volta %P{FFFFFF}! Por favor, introduza sua senha no campo abaixo.\n\n{FFFF00}Tenha um otimo jogo :)", "{FFFFFF}Welcome Back %P{FFFFFF}, Please log into to your account below!\n\n{FFFF00}Enjoy your stay :)"},
{"player/account/login/dialog-title", "Logar na sua Conta:", "Login To Your Account"},
{"player/account/login/wrong-password", "Senha incorreta! %d de 5 tentativas", "Incorrect password! %d out of 5 tries"},
{"player/account/register/dialog-body", "{FFFFFF}Ola %P{FFFFFF}, Você deve ser novo aqui!\n\nCrie uma conta digitando uma {33CCFF}senha{FFFFFF} abaixo:", "{FFFFFF}Hello %P{FFFFFF}, You must be new here!\nPlease create an account by entering a {33CCFF}password{FFFFFF} below:"},
{"player/account/register/dialog-title", "Cadastre-se para uma nova conta", "Register For A New Account"},
{"player/account/register/invalid-password", "Senha inválida. Tem que ser entre 6 a 32 caracteres", "Invalid password. It needs to be between 6 and 32 characters."},
{"player/aimshout-set", " >  AimShout setado para '%s'", " >  AimShout set to '%s'"},
{"player/aimshout", " >  Use: /aimshout [texto] - Crie um texto personalizado para aimshout. Apertando botão direito e scroll do mouse ao mesmo tempo.", " >  Usage: /aimshout [text] - Sets a custom string you can send by pressing the AIM and LOOK BEHIND keys at the same time."},
{"player/alive-time", "Tempo Vivo", "Time Alive"},
{"player/bag/extra-slots", "Precisa de %d slots extras na mochila", "Extra %d backpack slots required"},
{"player/bag/item-added", "Item adicionado na mochila", "Item added to backpack"},
{"player/changepassword/error", " >  Aconteceu um erro! Por favor, contate o administrador.", " >  An error occurred! Please contact an administrator"},
{"player/changepassword/no-match", " >  A senha que você digitou radio coincide com a sua senha atual.", " >  The entered password you typed doesnt match your current password."},
{"player/changepassword/success", "Chave alterada com sucesso", "Password changed succesfully"},
{"player/changepassword/syntax", " >  Use: /mudarsenha [senha antiga] [nova senha]", " >  Usage: /changepass [old pass] [new pass]"},
{"player/chat/in-tutorial", "Não ter permissão para utilizar o chat, enquanto se encontra no Tutorial. Se tiver alguma duvida utilize o Discord.", "You don't have permission to chat in the Tutorial. Use the Discord if you have questions."},
{"player/chat/mode/already-tip", "Você ja se encontra nesse modo de chat. Não necessita de utilizar comando para escrever", "You're already in that Chat Mode. You don't need to use a command to chat"},
{"player/chat/mode/already", "Você ja se encontra nesse modo de chat", "You're already in that Chat Mode"},
{"player/deathcount", "Vezes Morto", "Amount of Deaths"},
{"player/frozen", " >  Congelado pelo administrador", " >  Frozen by admin"},
{"player/gender/female", "Mulher", "Female"},
{"player/gender/male", "Homem", "Male"},
{"player/health/dieing/food", "~r~Você ira comecar a morrer de fome! Fome: %.1f%%", "~r~You will start to starve! Hunger: %.1%%"},
{"player/health/poisened/food", " Infecao Alimentar", " Food Poisoning"},
{"player/health/status_ui/bleeding", "Sangramento", "Bleeding"},
{"player/health/status_ui/header", "Saude e Feridas", "Health and Wounds"},
{"player/health/status_ui/infections/food", "Infecao Alimentar", "Food Poisoning"},
{"player/health/status_ui/infections/wound", "Infecao na Ferida", "Infected Wound"},
{"player/health/status_ui/inventory/slotback", "Costas", "Back"},
{"player/health/status_ui/inventory/slotcold", "Coldre", "Holster"},
{"player/health/status_ui/inventory/slotface", "Rosto", "Face"},
{"player/health/status_ui/inventory/slothand", "Mao", "Hand"},
{"player/health/status_ui/inventory/slothead", "Cabeca", "Head"},
{"player/health/status_ui/inventory/slottors", "Corpo", "Torso"},
{"player/health/wounded", "Ferido: %s~n~Gravidade: %s", "Wounded: %s~n~Severity: %s"},
{"player/health/wounds/cured", "Curado %d feridas", "Healed %d wounds"},
{"player/health/wounds/infected", "~y~Sua ferida agora esta infectada", "Your wound has become infected!"},
{"player/holster/change", "Arma Trocada", "Weapon Changed"},
{"player/holster/equip", "Equipado", "Equipped"},
{"player/holster/put", "Arma Colocada no Coldre", "Weapon Holstered"},
{"player/interaction", "Pressione F para interagir", "Press F to Interact"},
{"player/inventory/armour-removed", "Colete removido", "Armour removed"},
{"player/inventory/camouflage", "{FFFF00}Camuflagem >", "{FFFF00}Cammouflage >"},
{"player/inventory/friends/accept", " > Use /aceitar [id do jogador]", " > Use /accept [player id]"},
{"player/inventory/friends/add", "Adicionar um amigo +", "Add a friend +"},
{"player/inventory/friends/friend-no-invite", " > Esse jogador radio enviou nenhum pedido de amizade.", " > This player has not sent any friend invitations."},
{"player/inventory/friends/friend-offline", " > ID de jogador não conectado.", " > Player ID not logged in."},
{"player/inventory/friends/invited", "Convite de amigo enviado com sucesso.", "Friendship invitation sent successfully."},
{"player/inventory/friends/max-friends", "Você atingiu o limite maximo de amigos", "You have reached the maximum number of friends."},
{"player/inventory/friends/option", "{33AA33}Amigos >{FFFFFF}", "{33AA33}Friends >{FFFFFF}"},
{"player/inventory/friends/remove", "{E85454}Você quer mesmo remover esse amigo da sua lista de amigos?", "{E85454}Do you want to remove this friend from your friends list?"},
{"player/inventory/friends/titulo", "{33AA33}Amigos", "{33AA33}Friends"},
{"player/inventory/hat-removed", "Chapeu removido", "Hat removed"},
{"player/inventory/holding-item", "~y~Você ja esta segurando um item", "You are already holding an item"},
{"player/inventory/item-added", "Item adicionado ao inventario", "Item added to inventory"},
{"player/inventory/mask-removed", "Mascara removida", "Mask removed"},
{"player/inventory/slots/back", "Costas", "Back"},
{"player/inventory/slots/face", "Cara", "Face"},
{"player/inventory/slots/hand", "Mao", "Hand"},
{"player/inventory/slots/head", "Cabeca", "Head"},
{"player/inventory/slots/holster", "Coldre", "Holster"},
{"player/inventory/slots/torso", "Tronco", "Torso"},
{"player/join-sentence/big-sentence", " > Frase muito grande.", " > Phrase too very long."},
{"player/join-sentence/changed", " > Frase de entrada alterada para: ", " > Entry phrase changed to: "},
{"player/join-sentence/onplayerlogin", " > Sua frase de entrada", " > Your entrance sentence"},
{"player/join", "%P (%s) {FFFFFF}entrou no servidor %s", "%P (%s) {FFFFFF}joined the server %s"},
{"player/key-actions/item/dropreload-weapon", "Dropar/Recarregar", "Drop/Reload"},
{"player/key-actions/item/fill-petrolcan", "Encher o Galao", "Fill up the Gallon"},
{"player/key-actions/items/arm_explosive", "Armar Explosivo", "Arm Explosive"},
{"player/key-actions/items/fill_jerrycan", "Encher Galao", "Fill Jerry Can"},
{"player/key-actions/items/take_pills", "Tomar Comprimidos", "Take Pills"},
{"player/key-actions/items/use-acessory", "Usar Acessorio", "Use Acessory"},
{"player/key-actions/items/use", "Usar", "Use"},
{"player/key-actions/items/equip", "Equipar", "Equip"},
{"player/key-actions/items/weapon_reload", "Recarregar Arma", "Reload Weapon"},
{"player/key-actions/items/weapon_unload", "Descarregar Arma", "Unload Weapon"},
{"player/key-actions/player/apply_cuffs", "Algemar", "Cuff"},
{"player/key-actions/player/disassemble", "Desmontar", "Disassemble"},
{"player/key-actions/player/drink", "Beber", "Drink"},
{"player/key-actions/player/eat", "Comer", "Eat"},
{"player/key-actions/player/heal_me", "Curar-se", "Heal Me"},
{"player/key-actions/player/heal_player", "Curar Jogador", "Heal Player"},
{"player/key-actions/player/holster-get", "Pegar do Coldre", "Pick the Holster"},
{"player/key-actions/player/holster", "Colocar no Coldre", "Holster"},
{"player/key-actions/player/inject_me", "Injete-se", "Inject Me"},
{"player/key-actions/player/inject_player", "Injetar Jogador", "Inject Player"},
{"player/key-actions/player/item_drop", "Soltar Item", "Drop Item"},
{"player/key-actions/player/item_give", "Dar Item", "Give Item"},
{"player/key-actions/player/open_bag", "Abrir Mochila", "Open Backpack"},
{"player/key-actions/player/open_inventory", "Abrir Inventario", "Open Inventory"},
{"player/key-actions/player/open_map", "Abrir Mapa", "Open Map"},
{"player/key-actions/player/remove_bag", "Remover Mochila", "Remove Backpack"},
{"player/key-actions/player/remove_cuffs", "Remover Algemas", "Remove Cuffs"},
{"player/key-actions/player/set_sign", "Colocar Placa", "Set Sign"},
{"player/key-actions/player/unholster", "Remover do Coldre", "Unhoster"},
{"player/key-actions/player/use_shield", "utilizar Escudo", "Use Shield"},
{"player/key-actions/player/wear_clothes", "Vestir Roupas", "Wear Clothes"},
{"player/key-actions/player/wear_vest", "Vestir Colete", "Wear Vest"},
{"player/key-actions/rank/kills", "Mortes", "Kills"},
{"player/key-actions/rank/time-alive", "Tempo Vivo", "Time alive"},
{"player/key-actions/vehicle/open_trunk", "Abrir Porta-Malas", "Open Trunk"},
{"player/key-actions/vehicle/refuel", "Reabastecer", "Refuel"},
{"player/key-actions/vehicle/repair-engine", "Reparar com Ferramenta", "Repair with a Tool"},
{"player/key-actions/vehicle/replace_light", "Substituir Farol", "Replace Light"},
{"player/key-actions/vehicle/replace_tyre", "Substituir Roda", "Replace Tyre"},
{"player/key-actions/vehicle/toggle_doors", "Portas", "Doors"},
{"player/key-actions/vehicle/toggle_engine", "Motor", "Engine"},
{"player/key-actions/vehicle/toggle_horn", "Buzina", "Horn"},
{"player/key-actions/vehicle/toggle_lights", "Farois", "Lights"},
{"player/kicked", "Kickado(a): {33CCFF}%s", "Kicked: {33CCFF}%s"},
{"player/left-crash", "%P perdeu a conexão ou crashou", "%P either crashed or lost connection"},
{"player/left", "%P saiu do servidor", "%P left the server"},
{"player/mute-timer", " >  Você esta mudo. Tempo restante: %s", " >  You are muted. Time remaining: %s"},
{"player/muted-perm", " >  Você esta permanentemente mudo.", " >  You are muted permanently."},
{"player/muted-reas", " >  Mutado do chat global, Razao: {33CCFF}%s", " >  Muted from global chat, Reason: {33CCFF}%s"},
{"player/muted-temp", " >  Mutado no chat global por {FFAA00}30 {E85454}segundos por flood.", " >  Muted from global chat for {FFAA00}30 {E85454}seconds for chat flooding"},
{"player/muted-time", " >  Mutado do chat global por {FFAA00}%d {FFFF00}segundos, Razão: {33CCFF}%s", " >  Muted from global chat for {FFAA00}%d {FFFF00}seconds, Reason: {33CCFF}%s"},
{"player/not-found", " > O jogador radio pode ser encontrado.", " > The player cannot be found."},
{"player/ping", "Ping muito alto", "Ping too high"},
{"player/radio/admin", " > Admin chat ativado.", " > Admin chat activated."},
{"player/radio/freq", " >  Você ligou seu radio na frequencia %.2f.", " >  You turned your radio on to frequency %.2f."},
{"player/radio/global-quiet-off", " >  Você ligou o receptor global do seu radio, agora você vera todo o chat global.", " >  You turn on your radio's global receiver, you will now see all global chat."},
{"player/radio/global-quiet", " >  Você desligou o receptor global do seu radio, você radio vera mais o chat global.", " >  You turn off your radio's global receiver, you will not see any global chat."},
{"player/radio/global", " >  Você ligou seu radio na frequencia global.", " >  You turn your radio on to the global frequency."},
{"player/radio/local", " >  Você ligou o seu radio na frequencia local.", " >  You turned your radio on to the local frequency."},
{"player/radio/not-synced", "Radio radio sincronizado", "Radio not synchronized."},
{"player/reducebleed", "Taxa de sangramento reduzida de %f para %f", "Reduced bleedrate from %f to %f"},
{"player/tips/off", " >  Dicas desativadas", " >  Tooltips disabled"},
{"player/tips/on", " >  Dicas ativadas", " >  Tooltips enabled"},
{"player/unfrozen", "Esta agora Descongelado", "You are now Unfrozen"},
{"player/unmuted", " >  Agora você esta habilitado a falar.", " >  You are now un-muted."},
{"player/warn-counter", " >  Você tem %d/5 avisos!", " >  You have %d/5 warnings!"},
{"player/warned", " >  Você foi advertido (%d/5) por: %s. 5 avisos = 1 dia de ban!", " >  You been warned (%d/5) for: %s. 5 warnings = 1 day ban!"},
{"puzzle/codehunt/nearby-key", "Essa porta esta eletronicamente trancada e controlada por um teclado proximo.", "This door is electronically locked controlled by a nearby keypad."},
{"server/bugs/bug-description", "Escreva uma breve descricao do bug e como reproduzi-lo. Em seguida siga o report no Discord.", "Write a short description of the bug and how to reproduce it. Follow up on it on Discord."},
{"server/bugs/failed", "A sua submissao de bug falhou.", "Failed."},
{"server/bugs/submitted", " >  Seu relatorio de bug foi enviado! Obrigado pelo seu feedback! Você pode ver uma lista com os problemas em /bugs.", " >  Your bug report has been submitted! Thank you for your feedback! You can view a list of current issues with /bugs."},
{"server/clock", "RESPAWN EM", "RESTARTING IN"},
{"server/command/cant-use-not-logged-in", " >  Você precisa estar logado para usar esse comando", " >  You must be logged in to use that command"},
{"server/command/cant-use-player", "Você não pode usar esse comando neste jogador agora.", "You cannot use that command on that player right now."},
{"server/command/cant-use", "Você não pode usar esse comando agora.", "You cannot use that command right now."},
{"server/command/help", "\t/ajudavip - Ver os beneficios e valores do VIP\n\n\t/ajudaclan - Lista de comandos de clan do servidor\n\n\t/crafts - Lista de crafts do servidor\n\n\t/rank - Veja o ranking do servidor\n\n\t/dicas - Habilite e desabilite as dicas de ajuda\n\n\t/mudarsenha - Alterar sua senha\n\n\t/relatorio [mensagem] - Envie uma mensagem para os administradores do servidor\n\n\t/regras - Ver as regras do servidor\n\n\t/discord - Ver o link do nosso grupo no Discord\n\n\t/bug - Reportar algum BUG para os staffs\n\n\t/report - Reportar algum jogador\n\n\t/explosivos - Ver a lista de explosivos do servidor\n\n\t/metais - Ver a lista de metais do servidor\n\n\t/mochilas - Ver a lista de mochilas do servidor\n\n\t/caixas - Ver a lista de caixas do servidor", "\t/viphelp - See the VIP benefits/values\n\n\t/crafts - List of server crafts\n\n\t/rank - View server rank.\n\n\t/tooltips - Enables and disables server hints.\n\n\t/changepass - change your password\n\n\t/relatorio [message] - Send a message to server administrators\n\n\t/rules - View the rule list\n\n\t/discord - View the link of discord group\n\n\t/bug - Report any BUG for staffs\n\n\t/report - Report any player for staffs\n\n\t/explosives - View server explosives list\n\n\t/defences - View server defences list\n\n\t/backpacks - View server backpacks list\n\n\t/boxes - View server box list."},
{"server/command/invalid-player", "ID/Nick invalido", "Invalid ID/Nickname"},
{"server/command/lists/backpacks", "\t{FFFF00}Lista de Mochilas: (Total: 7)\n\n\t{FFAA00}Mochila de Acampamento - (18 slots)\n\n\t{FFAA00}Mochila de Paraquedas - (15 slots)\n\n\t{FFAA00}Mochila Grande - (14 slots)\n\n\t{FFAA00}Mochila Larga - (12 slots)\n\n\t{FFAA00}Mochila Media - (10 slots)\n\n\t{FFAA00}Daypack - (8 slots)\n\n\t{FFAA00}Mochila Pequena - (7 slots).", "\t{FFFF00}List of Backpacks: (Total: 7)\n\n\t{FFAA00}Mochila de Acampamento - (18 slots)\n\n\t{FFAA00}Mochila de Paraquedas - (15 slots)\n\n\t{FFAA00}Mochila Grande - (14 slots)\n\n\t{FFAA00}Mochila Larga - (12 slots)\n\n\t{FFAA00}Mochila Media - (10 slots)\n\n\t{FFAA00}Daypack - (8 slots)\n\n\t{FFAA00}Mochila Pequena - (7 slots)."},
{"server/command/lists/bombs", "\t{FFFF00}Lista de Explosivos: (Total: 2)\n\n\t{FFAA00}DINAMITE - (3 DE DANO EM METAIS)\n\n\t{FFAA00}TNT - (2 DE DANO EM METAIS)\n\n\t{FFAA00}IED - (1 DE DANO EM METAIS).", "\t{FFFF00}List of Explosives: (Total: 2)\n\n\t{FFAA00}TNT - (2 DAMAGE IN DEFENCES)\n\n\t{FFAA00}IED - (1 DAMAGE IN DEFENCES)."},
{"server/command/lists/boxes", "\t{FFFF00}Lista de Caixas: (Total: 8)\n\n\t{FFAA00}Armario (45 Slots)\n\n\t{FFAA00}Caixa Grande (15 Slots)\n\n\t{FFAA00}Caixa Media (12 Slots)\n\n\t{FFAA00}Caixa Pequena (10 Slots)\n\n\t{FFAA00}Caixa de Ferramentas (8 Slots)\n\n\t{FFAA00}Mala de Viagem (6 Slots)\n\n\t{FFAA00}Bolsa de Viagem (6 Slots)\n\n\t{FFAA00}Caixinha (5 Slots).", "\t{FFFF00}List of Boxes: (Total: 8)\n\n\t{FFAA00}Armario (45 Slots)\n\n\t{FFAA00}Caixa Grande (15 Slots)\n\n\t{FFAA00}Caixa Media (12 Slots)\n\n\t{FFAA00}Caixa Pequena (10 Slots)\n\n\t{FFAA00}Caixa de Ferramentas (8 Slots)\n\n\t{FFAA00}Mala de Viagem (6 Slots)\n\n\t{FFAA00}Bolsa de Viagem (6 Slots)\n\n\t{FFAA00}Caixinha (5 Slots)."},
{"server/command/lists/defences", "\t{FFFF00}Lista de Metais: (Total: 17)\n\n\t{FFAA00}Metal Blindado - (15/15)\n\n\t{FFAA00}Porta Blindada (14/14)\n\n\t{FFAA00}Porta de Cofre (13/13)\n\n\t{FFAA00}Portão de Garagem (12/12)\n\n\t{FFAA00}Porta Dupla - (11/11)\n\n\t{FFAA00}Porta de Navio - (9/9)\n\n\t{FFAA00}Metal Corrugado - (8/8)\n\n\t{FFAA00}Painel Isolado - (8/8)\n\n\t{FFAA00}Rampa de Madeira - (8/8)\n\n\t{FFAA00}Entrada Isolada - (7/7)\n\n\t{FFAA00}Grade Grande - (7/7)\n\n\t{FFAA00}Painel de Metal - (6/6)\n\n\t{FFAA00}Porta de Container - (6/6)\n\n\t{FFAA00}Grade - (5/5)\n\n\t{FFAA00}Pedaco de Metal - (4/4)\n\n\t{FFAA00}Metal Pequeno - (4/4).", "\t{FFFF00}Lista de Metais: (Total: 17)\n\n\t{FFAA00}Metal Blindado - (15/15)\n\n\t{FFAA00}Porta Blindada (14/14)\n\n\t{FFAA00}Porta de Cofre (13/13)\n\n\t{FFAA00}PortÃƒÆ’Ã‚Â£o de Garagem (12/12)\n\n\t{FFAA00}Porta Dupla - (11/11)\n\n\t{FFAA00}Porta de Navio - (9/9)\n\n\t{FFAA00}Metal Corrugado - (8/8)\n\n\t{FFAA00}Painel Isolado - (8/8)\n\n\t{FFAA00}Rampa de Madeira - (8/8)\n\n\t{FFAA00}Entrada Isolada - (7/7)\n\n\t{FFAA00}Grade Grande - (7/7)\n\n\t{FFAA00}Painel de Metal - (6/6)\n\n\t{FFAA00}Porta de Container - (6/6)\n\n\t{FFAA00}Grade - (5/5)\n\n\t{FFAA00}Pedaco de Metal - (4/4)\n\n\t{FFAA00}Metal Pequeno - (4/4)."},
{"server/command/lists/rules", "\t{FFFF00}List of Rules: (Total: 9)\n\n\t{FFAA00}1. Disrespect for staff = ban\n\n\t{FFAA00}2. Player offense or disrespect = warn\n\n\t{FFAA00}3. Promote other servers = ban\n\n\t{FFAA00}4. Bug abuse = ban (depending on severity)\n\n\t{FFAA00}5. Report players in global chat = warn\n\n\t{FFAA00}6. Use beneficial programs or mods = ban\n\n\t{FFAA00}7. Have more than one account on server = account disabled and warn\n\n\t{FFAA00}8. FakeKill (kill friends or clan members) = warn\n\n\t{FFAA00}9. Flood/Spam = warn.", "\t{FFFF00}List of Rules: (Total: 9)\n\n\t{FFAA00}Disrespect for staff = ban\n\n\t{FFAA00}Player offense or disrespect = warn\n\n\t{FFAA00}Promote other servers = ban\n\n\t{FFAA00}Bug abuse = ban (depending on severity)\n\n\t{FFAA00}Report players in global chat = warn\n\n\t{FFAA00}Use beneficial programs or mods = ban\n\n\t{FFAA00}Have more than one account on server = account disabled and warn\n\n\t{FFAA00}FakeKill (kill friends or clan members) = warn\n\n\t{FFAA00}Flood/Spam = warn."},
{"server/command/need-duty", "Você so pode usar esse comando em {33CCFF}Duty{E85454}.", "You can only use that command while on {33CCFF}administrator duty{E85454}."},
{"server/command/no-permission", "Você não tem autoridade suficiente para usar esse comando.", "You have insufficient authority to use that command."},
{"server/command/unknown", "Esse não e um comando conhecido. Cheque o comando de ajuda: {33CCFF}/ajuda", "That is not a recognized command. Check the {33CCFF}/help {FFAA00}dialog."},
{"server/drop/supply-request", "[Exercito]: %p (%d) SOLICITOU UMA CAIXA DE SUPRIMENTOS: {33CCFF}%s {FFFF00} MARCADO UM 'S' NO MAPA!", "[ARMY]: %p (%d) REQUESTED A SUPPLY DROP: {33CCFF}%s MARKED WITH A 'S' ICON ON MAP!"},
{"server/drop/supply", "[Exercito]: CAIXA DE SUPRIMENTOS: {33CCFF}%s {FFFF00}CAINDO EM: {FFAA00}%s", "[ARMY]: SUPPLY DROP: {33CCFF}%s {FFFF00}FALLING INTO: {FFAA00}%s"},
{"server/drop/weapons", "[Exercito]: CAIXA DE ARMAMENTOS CAINDO EM: {FFAA00}%s", "[ARMY]: BOX OF WEAPONS FALLING INTO: {FFAA00}%s"},
{"server/motd", "Mensagem do Dia", "Message of the Day"},
{"server/restart_warning_1m", " > AVISO: O respawn de itens ocorrera em 1 minutos. Saia para evitar bugs!", " > WARNING: Item respawn will occur in 1 minutes. Log out to avoid bugs!"},
{"server/restart_warning_3m", "> AVISO: O respawn de itens ocorrera em 3 minutos. Saia para evitar bugs!", "> WARNING: Item respawn will occur in 3 minutes. Log out to avoid bugs!"},
{"tutorial/exit", "Você saiu do tutorial. Boa sorte tentando sobreviver.", "You left the tutorial. Have fun trying to survive."},
{"tutorial/intro", "Bem-vindo ao tutorial! Olhe ao redor e tente coisas. As mensagens de ajuda aparecerao aqui!", "Welcome to the tutorial! Look around and try things. Help messages will appear here!"},
{"tutorial/intro-more", "Se se sentir preso em algum passo envie '/pm' a algum '/admins' ou fale no #bate-papo no Discord!", "If you are feeling stuck in any step ask for help in #bate-papo on Discord."},
{"tutorial/step/add_item_to_container", "Adicionar Item a Mochila", "Add Item to Backpack"},
{"tutorial/step/add_item_to_inventory", "Adicionar Item ao Inventario", "Add Item to Inventory."},
{"tutorial/step/build_tent", "Montar Tenda", "Build Tent"},
{"tutorial/step/drop_item", "Dropar Item", "Drop Item"},
{"tutorial/step/equip_backpack", "Equipar Mochila", "Equip Backpack"},
{"tutorial/step/finish_item_tweak", "Terminar Edicao da Defesa", "Finish Defence Edit"},
{"tutorial/step/holster_weapon", "Colocar Arma no Coldre", "Put Weapon in Holster"},
{"tutorial/step/open_container", "Abrir Mochila", "Open Backpack"},
{"tutorial/step/open_inventory", "Abrir Inventario", "Open Inventory"},
{"tutorial/step/repair_vehicle", "Reparar Veiculo", "Repair Vehicle"},
{"tutorial/step/use_item_on_another_item", "Construir Metal Corrugado", "Construct Metal Corrugado"},
{"tutorial/step/view_container_options", "Abrir Opcoes da Mochila", "Open Backpack Options"},
{"tutorial/step/view_inventory_options", "Abrir Opcoes do Inventario", "Open Inventory Options"},
{"tutorial/tip/access_bag_own", "Esta e a sua Mochila. Elas serão armazenamento extra. Existem muitos tipos diferentes de mochilas com tamanhos diferentes.", "This is your bag. Bags are extra storage. There are many different types of bags with different sizes."},
{"tutorial/tip/access_bag", "Você pode acessar sua mochila pressionando H e clicando no icone da Mochila na parte inferior direita.", "You can access your backpack by pressing H and clicking the backpack icon at the bottom right."},
{"tutorial/tip/access_inventory", "Este e o seu inventario. Tambem conhecido como seus bolsos. Esta não e sua mochila.", "This is your character inventory also known as your pockets. This is not your bag."},
{"tutorial/tip/defence", "Acabamento da defesa finalizado. Instale um motor e depois um teclado em sua defesa.", "Finished defense finished. Install a motor and then a keyboard in your defense."},
{"tutorial/tip/item-add-bag", "Você adicionou um item a sua mochila. Você pode acessar sua mochila pressionando H e clicando no icone da Mochila na parte inferior direita.", "You added an item to your bag. You can access your bag by pressing H and clicking the Bag icon at the bottom right."},
{"tutorial/tip/item-add-container", "Você adicionou um item a um container. Os containeres serão lugares para armazenar itens", "You added an item to a container. Containers are places to store items"},
{"tutorial/tip/item-add", "Você adicionou um item ao seu inventario. Se o seu inventario estiver cheio, o item será colocado na sua Mochila.", "You added an item to your inventory. If your inventory is full, the item will be put in your bag."},
{"tutorial/tip/item-drop", "Quando você soltar um item, outros jogadores podem pega-lo.", "When you drop an item, other players can pick it up."},
{"tutorial/tip/item-options", "Estas serão suas opcoes para o item selecionado. Clique duas vezes em alguma para executar.", "These are your options for the selected item. Equip puts it in your hand. Combine can be selected on multiple items to attempt to combine them."},
{"tutorial/tip/item-use-item", "Você tentou usar um item em outro item. Isso pode ser usado as vezes, por exemplo, use um isqueiro com uma fogueira para acende-la. ou use uma arma em uma municao para carrega-la.", "You tried to use an item with another item because you are holding one already. This can be used sometimes, for example use a lighter with a campfire to light it or use a weapon with ammo to load it."},
{"tutorial/tip/tent-built", "Você construiu agora uma tenda. Pode utilizar ela para salvar alguns dos seus itens.", "You built a Tent. You can use these to save some of your items."},
{"tutorial/tip/vehicle-hammer", "Este veiculo esta um pouco quebrado! Para reparar, equipe um martelo e segure ~y~F ~w~na frente do veiculo.", "This vehicle is a bit broken! To fix, equip a hammer and hold ~y~F ~w~while at the front of the vehicle."},
{"tutorial/tip/vehicle-screwdriver", "Este veiculo esta quebrado! Para reparar, equipe uma chave de fenda e segure ~y~F ~w~na frente do veiculo.", "This vehicle is broken! To fix, equip a screwdriver and hold ~y~F ~w~while at the front of the vehicle."},
{"tutorial/tip/vehicle-spanner", "Este veiculo esta ligeiramente quebrado! Para consertar, equipe uma chave inglesa e segure ~y~F ~w~enquanto estiver na frente do veiculo.", "This vehicle is slightly broken! To fix, equip a wrench and hold ~y~F ~w~while at the front of the vehicle."},
{"tutorial/tip/vehicle-wrench", "Este veiculo esta muito quebrado! Para reparar, equipe uma chave de roda e segure ~y~F ~w~na frente do veiculo.", "This vehicle is very broken! To fix, equip a wrench and hold ~y~F ~w~while at the front of the vehicle."},
{"tutorial/tip/weapon-holster", "Você colocou um item no coldre. Os itens no coldre podem ser rapidamente acessados pressionando Y novamente.", "You have holstered an item. Holstered items can be quickly accessed by pressing Y again."},
{"vehicle/hud/damage", "Dano", "Damage"},
{"vehicle/hud/door_state", "Portas", "Doors"},
{"vehicle/hud/engine_state", "Motor", "Engine"},
{"vehicle/lock/already", "Este veiculo ja esta trancado", "That vehicle has already been locked"},
{"vehicle/lock/break-start", "Arrombando porta do veiculo", "Breaking Vehicle Door"},
{"vehicle/lock/chain_no-key", "Essa Corrente não tem chave. Combine com um Kit Chaveiro.", "That lock and chain has no key. Combine it with a Locksmith Kit."},
{"vehicle/lock/door-locked-persn", "Porta bloqueada com bloqueio personalizado", "Door locked with custom lock"},
{"vehicle/lock/door-locked", "Porta trancada ~n~ Use um Pe de Cabra", "Door locked~n~Use a Crowbar"},
{"vehicle/lock/key_uncut", "Essa chave ainda não foi cortada.", "That key hasnt been cut yet."},
{"vehicle/lock/key_wrong", "Essa chave não serve neste veiculo", "That key doesnt fit this vehicle"},
{"vehicle/lock/locked-trunk", "Porta-malas trancado", "Trunk Locked"},
{"vehicle/lock/locked", "Este veiculo esta trancado", "This vehicle are locked"},
{"vehicle/lock/no-lock", "Esse veiculo ainda não tem uma chave. Use Kit Chaveiro para por uma.", "That vehicle lock hasnt been set up for a key yet. Use a Locksmith Kit to set it up."},
{"vehicle/lock/no=doors", "Você não pode trancar um veiculo que não tem portas.", "You cannot lock a vehicle with no doors"},
{"vehicle/lock/trunk-break-start", "Arrombando porta-malas do veiculo", "Breaking Vehicle Trunk"},
{"vehicle/lock/unbreakable", "Este veiculo foi travado com uma chave craftada e não pode ser quebrado", "This vehicle has been locked with a crafted lock and cannot be broken"},
{"vehicle/lock/unlocked", "Destrancado", "Unlocked"},
{"vehicle/repair/body/fixed", "O veiculo e a lataria foi reparada.", "The vehicle and body has been fixed."},
{"vehicle/repair/tool/another", "Você precisa de outra ferramenta", "You need another tool"},
{"vehicle/repair/wheel/closer", "Chegue perto de uma roda para reparar", "Interact with a wheel to repair it"},
{"vehicle/repair/wheel/not-flat", "Este pneu não esta furado", "Tire not flat"},
{"vehicle/repair/wheel/replace/back", "Substituindo Roda Traseira", "Replacing the back Wheel"},
{"vehicle/repair/wheel/replace/front-left", "Substituindo Roda Dianteira Esquerda", "Replacing Front Left Wheel"},
{"vehicle/repair/wheel/replace/front-right", "Substituindo Roda Dianteira Direita", "Replacing Front Right Wheel"},
{"vehicle/repair/wheel/replace/front", "Substituindo Roda Dianteira", "Replacing the front Wheel"},
{"vehicle/repair/wheel/replace/rear-left", "Substituindo Roda Traseira Esquerda", "Replacing Rear Left Wheel"},
{"vehicle/repair/wheel/replace/rear-right", "Substituindo Roda Traseira Direita", "Replacing Rear Right Wheel"},
{"vehicle/repair/wheel/replace/replaced", "Roda Substituida", "Wheel Replaced"},
{"vehicle/saved", "Veiculo %s salvo!", "Vehicle %s saved!"}